;(defvar hp-melpa-url "http://melpa.milkbox.net/packages/")
(defvar hp-melpa-url "https://melpa.org/packages/")
(defvar hp-melpa-stable-url "https://stable.melpa.org/packages/")
(defvar hp-marmalade-url "http://marmalade-repo.org/packages/")
(defvar hp-org-url "https://orgmode.org/elpa/")
;(defvar hp-use-package-list '())
(require 'package)
(add-to-list 'package-archives '(cons "melpa" hp-melpa-url))
(add-to-list 'package-archives '(cons "melpa-stable" hp-melpa-stable-url))
(add-to-list 'package-archives '(cons "marmalade" hp-marmalade-url))
;(add-to-list 'package-archives '(cos "org" hp-org-url))
